# Generated by Django 4.2.4 on 2023-08-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_locked',
        ),
    ]
