# Generated by Django 4.2.4 on 2023-08-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(default='Anonymous', max_length=64),
            preserve_default=False,
        ),
    ]
