# Generated by Django 4.2.4 on 2023-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
